# Site settings
title: LOFOXO Blog
SEOTitle: 发祥博客|LOFOXOBlog
header-img: img/home-bg.jpg
email: tutuzuo@gmail.com
description: "旅程，拨开世界迷雾的日记"
keyword: "unity，游戏，场景"
url: "http://lofoxo.github.io/blog.github.io"              # your host, for absolute URL
baseurl: /blog.github.io                         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     lofoxo
#zhihu_username:     tutuzuo
github_username:    LOFOXO
#facebook_username:  LOFOXO



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: LOFOXO
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 55df67e33b8c615be71a335c9a953613
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: auto




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "想想游戏，做做游戏，玩玩游戏"
sidebar-avatar: img/avatar-head.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "My CSDN",
        href: "http://blog.csdn.net/tutuzuo"

    },
    {
        title: "shader_candycat",
        href: "http://candycat1992.github.io/"
    }
]
